version: 0.3.0-alpha.{build}
os: Visual Studio 2017 RC
environment:
  global:
    api_key:
      secure: ctO8SSBk8Mz45RIZ0x2/t3JSPLqr2UjD/u17pP4eLc9yCgY0KbIU0Mt1Aq1fhXvN
install:
- ps: .\build\install-dotnet.ps1
- dotnet restore
build_script:
- ps: dotnet restore .\src\BadMishka.GoDark\BadMishka.GoDark.csproj
- ps: dotnet restore .\test\BadMishka.GoDark.Tests\BadMishka.GoDark.Tests.csproj
- ps: dotnet build .\test\BadMishka.GoDark.Tests\BadMishka.GoDark.Tests.csproj -c Release --version-suffix $env:APPVEYOR_BUILD_NUMBER
- ps: dotnet pack .\src\BadMishka.GoDark\BadMishka.GoDark.csproj -c Release --version-suffix $env:APPVEYOR_BUILD_NUMBER
artifacts:
- path: 'artifacts\**\*.nupkg'
  name: nuget package
test_script: 
- ps: .\build\test.ps1
deploy_script:
- ps: .\build\deploy.ps1