version: 0.2.9-alpha.{build}
os: Visual Studio 2015
environment:
  global:
    api_key:
      secure: qlFhQA71WGw22mjjgFbj9e3MHTl0K3LRMlacBZWC6Eiqy85bAE0YGo+v/VM3wB5Y
install:
- ps: .\build\install-dotnet.ps1
- dotnet restore
build_script:
- ps: dotnet restore .\src\BadMishka.GoDark\project.json 
- ps: dotnet restore .\test\BadMishka.GoDark.Tests\project.json
- ps: dotnet build .\test\BadMishka.GoDark.Tests\project.json -c Release --version-suffix $env:APPVEYOR_BUILD_NUMBER
- ps: dotnet pack .\src\BadMishka.GoDark\project.json -c Release --version-suffix $env:APPVEYOR_BUILD_NUMBER
artifacts:
- path: 'artifacts\**\*.nupkg'
  name: nuget package
test_script: 
- ps: .\build\test.ps1
deploy_script:
- ps: .\build\deploy.ps1